<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.2</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>celements-spring-mvc</artifactId>
  <version>7.2-SNAPSHOT</version>
  <description>Celements Spring MVC</description>
  <dependencies>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-servlet</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-model</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>one.util</groupId>
      <artifactId>streamex</artifactId>
    </dependency>

    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-spring-security</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- open API / swagger -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-webmvc-core</artifactId>
    </dependency>
    <!-- Springdoc's ModelResolver loads XmlRootElement reflectively on Java 21. -->
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- test -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-shared-tests</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-subsystem-migration-manager</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>
  <scm>
    <connection>scm:git:git@github.com:celements/celements-spring.git</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-spring.git</developerConnection>
    <url>https://github.com/celements/celements-spring/celements-spring-mvc</url>
    <tag>HEAD</tag>
  </scm>
</project>
